openapi: 3.0.3
info:
  title: API de Facturación con GraphQL Proyecto Integrador DSW
  version: 1.0.0
  description: Documentación Swagger de todos los endpoints de la API de Facturación con GraphQL Proyecto Integrador DSW con servicios de notifacion via SMS, Whatsapp y e-mail.

servers:
  - url: http://localhost:4000/graphql
    description: Servidor local
  - url: https://proyectointegrador-dsw.onrender.com/playground
    description: Servidor principal de GraphQL

tags:
  - name: Clients
    description: Operaciones sobre clientes
  - name: Products
    description: Operaciones sobre los productos
  - name: Invoice
    description: Operaciones sobre la factura

paths:
  /graphql:
    post:
      tags:
        - GraphQL
      summary: Punto de entrada único para operaciones GraphQL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: |
                    query {
                      getAllClients {
                        id
                        legal_name
                        tax_id
                      }
                    }
                variables:
                  type: object
      responses:
        '200':
          description: Respuesta con los datos solicitados
        '400':
          description: Error en la sintaxis del query
