openapi: 3.0.3
info:
  title: API de Facturación con GraphQL - Proyecto Integrador DSW
  version: 1.0.0
  description: >
    Documentación Swagger de todos los endpoints de la API de Facturación con GraphQL.
    Incluye servicios de notificación vía SMS, WhatsApp y correo electrónico.

servers:
  - url: http://localhost:4000/graphql
    description: Servidor local
  - url: https://proyectointegrador-dsw.onrender.com/playground
    description: Servidor principal de GraphQL

tags:
  - name: Clients
    description: Operaciones sobre clientes
  - name: Products
    description: Operaciones sobre productos
  - name: Invoice
    description: Operaciones sobre facturas

paths:
  /graphql:
    post:
      tags:
        - GraphQL
      summary: Punto de entrada único para operaciones GraphQL
      description: >
        Utiliza este endpoint para ejecutar cualquier operación GraphQL: queries o mutations.
        En el campo `query`, coloca tu consulta o mutación GraphQL. En `variables`, pasa los valores requeridos si tu consulta los necesita.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
            examples:
              getAllClients:
                summary: Obtener todos los clientes
                value:
                  query: |
                    query {
                      getAllClients {
                        id
                        legal_name
                        tax_id
                        email
                        phone
                      }
                    }
              getClientById:
                summary: Obtener un cliente por ID
                value:
                  query: |
                    query {
                      getClientById(id: "cliente123") {
                        id
                        legal_name
                        tax_id
                        email
                        phone
                      }
                    }
              syncClientsFromFacturapi:
                summary: Sincronizar clientes desde Facturapi
                value:
                  query: |
                    query {
                      syncClientsFromFacturapi {
                        id
                        legal_name
                        tax_id
                      }
                    }
              createClient:
                summary: Crear un nuevo cliente
                value:
                  query: |
                    mutation CreateClient($input: ClientInput!) {
                      createClient(input: $input) {
                        id
                        legal_name
                        email
                      }
                    }
                  variables:
                    input:
                      legal_name: "Ejemplo S.A. de C.V."
                      tax_id: "ABC123456789"
                      email: "cliente@ejemplo.com"
                      phone: "5555555555"
                      address:
                        street: "Av. Central"
                        exterior: "10"
                        neighborhood: "Centro"
                        zip: "06000"
                        city: "CDMX"
                        municipality: "Benito Juárez"
                        state: "CDMX"
                        country: "MX"
              updateClient:
                summary: Actualizar un cliente existente
                value:
                  query: |
                    mutation UpdateClient($id: ID!, $input: UpdateClientInput!) {
                      updateClient(id: $id, input: $input) {
                        id
                        legal_name
                        email
                      }
                    }
                  variables:
                    id: "cliente123"
                    input:
                      legal_name: "Nuevo Nombre S.A. de C.V."
                      email: "nuevo@ejemplo.com"
              deleteClient:
                summary: Eliminar un cliente
                value:
                  query: |
                    mutation DeleteClient($id: ID!) {
                      deleteClient(id: $id)
                    }
                  variables:
                    id: "cliente123"
              getAllProducts:
                summary: Obtener todos los productos
                value:
                  query: |
                    query {
                      getAllProducts {
                        id
                        description
                        price
                      }
                    }
              getProductById:
                summary: Obtener un producto por ID
                value:
                  query: |
                    query {
                      getProductById(id: "producto123") {
                        id
                        description
                        price
                      }
                    }
              syncProductsFromFacturapi:
                summary: Sincronizar productos desde Facturapi
                value:
                  query: |
                    query {
                      syncProductsFromFacturapi {
                        id
                        description
                        price
                      }
                    }
              createProduct:
                summary: Crear un nuevo producto
                value:
                  query: |
                    mutation CreateProduct($input: ProductInput!) {
                      createProduct(input: $input) {
                        id
                        description
                        price
                      }
                    }
                  variables:
                    input:
                      description: "Producto de ejemplo"
                      product_key: "10101504"
                      price: 100.0
                      tax_included: true
                      taxes:
                        - type: "IVA"
                          rate: 0.16
                      unit_key: "H87"
                      sku: "PROD-001"
              updateProduct:
                summary: Actualizar un producto existente
                value:
                  query: |
                    mutation UpdateProduct($id: ID!, $input: UpdateProductInput!) {
                      updateProduct(id: $id, input: $input) {
                        id
                        description
                        price
                      }
                    }
                  variables:
                    id: "producto123"
                    input:
                      description: "Producto actualizado"
                      price: 120.0
              deleteProduct:
                summary: Eliminar un producto
                value:
                  query: |
                    mutation DeleteProduct($id: ID!) {
                      deleteProduct(id: $id)
                    }
                  variables:
                    id: "producto123"
              createInvoice:
                summary: Crear una factura
                value:
                  query: |
                    mutation CreateInvoice($input: InvoiceInput!) {
                      createInvoice(input: $input) {
                        id
                        status
                        pdf_url
                        xml_url
                        created_at
                      }
                    }
                  variables:
                    input:
                      customer: "cliente123"
                      items:
                        - quantity: 2
                          product: "producto123"
                      payment_form: "03"
                      payment_method: "PUE"
                      use: "G03"

