paths:
  /graphql:
    post:
      tags:
        - GraphQL
      summary: Punto de entrada único para operaciones GraphQL
      description: |
        Este endpoint permite enviar consultas (queries) y mutaciones (mutations) GraphQL para gestionar clientes, productos y facturas.

        Usa la sección `query` para especificar tu operación GraphQL, y opcionalmente `variables` si tu consulta lo requiere.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: |
                    query GetAllClients {
                      getAllClients {
                        id
                        legal_name
                        tax_id
                        email
                        phone
                      }
                    }
                variables:
                  type: object
      responses:
        '200':
          description: Respuesta con los datos solicitados
        '400':
          description: Error en la sintaxis del query
      x-codeSamples:
        - lang: GraphQL
          label: GetAllClients
          source: |
            query GetAllClients {
              getAllClients {
                id
                legal_name
                tax_id
                email
                phone
              }
            }

        - lang: GraphQL
          label: GetClientById
          source: |
            query GetClientById {
              getClientById(id: "cliente123") {
                id
                legal_name
                tax_id
                email
                phone
              }
            }

        - lang: GraphQL
          label: GetAllProducts
          source: |
            query GetAllProducts {
              getAllProducts {
                id
                product_key
                description
                price
                tax_included
              }
            }

        - lang: GraphQL
          label: GetProductById
          source: |
            query GetProductById {
              getProductById(id: "producto123") {
                id
                product_key
                description
                price
                tax_included
              }
            }

        - lang: GraphQL
          label: SyncClientsFromFacturapi
          source: |
            query SyncClients {
              syncClientsFromFacturapi {
                id
                legal_name
                tax_id
                email
                phone
              }
            }

        - lang: GraphQL
          label: SyncProductsFromFacturapi
          source: |
            query SyncProducts {
              syncProductsFromFacturapi {
                id
                description
                product_key
                price
              }
            }

        - lang: GraphQL
          label: CreateClient
          source: |
            mutation CreateClient {
              createClient(input: {
                legal_name: "Empresa S.A. de C.V.",
                tax_id: "ABC123456T12",
                email: "contacto@empresa.com",
                phone: "5555555555",
                address: {
                  street: "Av. Siempre Viva",
                  exterior: "123",
                  interior: "2B",
                  neighborhood: "Centro",
                  zip: "12345",
                  city: "Ciudad",
                  municipality: "Delegación",
                  state: "Estado",
                  country: "México"
                }
              }) {
                id
                legal_name
              }
            }

        - lang: GraphQL
          label: UpdateClient
          source: |
            mutation UpdateClient {
              updateClient(id: "cliente123", input: {
                email: "nuevo@correo.com"
              }) {
                id
                email
              }
            }

        - lang: GraphQL
          label: DeleteClient
          source: |
            mutation DeleteClient {
              deleteClient(id: "cliente123")
            }

        - lang: GraphQL
          label: CreateProduct
          source: |
            mutation CreateProduct {
              createProduct(input: {
                description: "Servicio de Consultoría",
                product_key: "84111506",
                price: 5000,
                tax_included: true,
                unit_key: "E48",
                sku: "SC001",
                taxes: [
                  {
                    type: "IVA",
                    rate: 0.16
                  }
                ]
              }) {
                id
                description
              }
            }

        - lang: GraphQL
          label: UpdateProduct
          source: |
            mutation UpdateProduct {
              updateProduct(id: "producto123", input: {
                price: 6000
              }) {
                id
                price
              }
            }

        - lang: GraphQL
          label: DeleteProduct
          source: |
            mutation DeleteProduct {
              deleteProduct(id: "producto123")
            }

        - lang: GraphQL
          label: CreateInvoice
          source: |
            mutation CreateInvoice {
              createInvoice(input: {
                customer: "cliente123",
                items: [
                  {
                    quantity: 2,
                    product: "producto123"
                  }
                ],
                payment_form: "03",
                payment_method: "PUE",
                use: "G03"
              }) {
                id
                status
                pdf_url
                xml_url
                created_at
              }
            }
