openapi: 3.0.3
info:
  title: API de Facturación con GraphQL Proyecto Integrador DSW
  version: 1.0.0
  description: Documentación Swagger de todos los endpoints de la API de Facturación con GraphQL Proyecto Integrador DSW con servicios de notifación via SMS, Whatsapp y e-mail.

servers:
  - url: http://localhost:4000/graphql
    description: Servidor local
  - url: https://proyectointegrador-dsw.onrender.com/playground
    description: Servidor principal de GraphQL

tags:
  - name: Clients
    description: Operaciones sobre clientes
  - name: Products
    description: Operaciones sobre los productos
  - name: Invoice
    description: Operaciones sobre la factura

paths:
  /graphql:
    post:
      tags:
        - GraphQL
      summary: Punto de entrada único para operaciones GraphQL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: |
                    query {
                      getInvoices {
                        id
                        uuid
                        folio
                        series
                        createdAt
                        total
                        client {
                          id
                          legal_name
                        }
                      }
                    }
                variables:
                  type: object
      responses:
        '200':
          description: Respuesta con los datos solicitados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      getInvoices:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: "665a6eced47639df2a99921f"
                            uuid:
                              type: string
                              example: "D6A8B31D-A76B-4F6E-BD28-FAAA23B79025"
                            folio:
                              type: integer
                              example: 123
                              description: Folio asignado por Facturapi a la factura
                            series:
                              type: string
                              example: "A"
                              description: Serie utilizada en la factura
                            createdAt:
                              type: string
                              format: date-time
                              example: "2025-06-01T19:45:20.000Z"
                            total:
                              type: number
                              format: float
                              example: 2560.5
                            client:
                              type: object
                              properties:
                                id:
                                  type: string
                                  example: "cl01"
                                legal_name:
                                  type: string
                                  example: "Empresa Ejemplo S.A. de C.V."
        '400':
          description: Error en la sintaxis del query
